"""Repository ports for organizations, memberships and invitations."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from nexusflow.core.pagination import Page, PageRequest
from nexusflow.domain.organizations.model import (
    Invitation,
    Membership,
    MembershipView,
    Organization,
    OrganizationView,
)


class OrganizationRepository(Protocol):
    async def add(self, org: Organization) -> None: ...

    async def get(self, org_id: UUID) -> Organization | None: ...

    async def get_for_update(self, org_id: UUID) -> Organization | None: ...

    async def slug_exists(self, slug: str) -> bool: ...

    async def list_for_user(self, user_id: UUID) -> list[OrganizationView]: ...


class MembershipRepository(Protocol):
    async def add(self, membership: Membership) -> None: ...

    async def get(self, org_id: UUID, user_id: UUID) -> Membership | None: ...

    async def get_by_id(self, org_id: UUID, membership_id: UUID) -> Membership | None: ...

    async def list_views(self, org_id: UUID, page: PageRequest) -> Page[MembershipView]: ...

    async def count_owners(self, org_id: UUID) -> int: ...

    async def delete(self, membership: Membership) -> None: ...

    async def first_for_user(self, user_id: UUID) -> Membership | None: ...

    async def list_org_ids_for_user(self, user_id: UUID) -> list[UUID]: ...


class InvitationRepository(Protocol):
    async def add(self, invitation: Invitation) -> None: ...

    async def get(self, org_id: UUID, invitation_id: UUID) -> Invitation | None: ...

    async def find_pending_by_email(self, org_id: UUID, email: str) -> Invitation | None: ...

    async def find_by_token_hash(self, token_hash: str) -> Invitation | None: ...

    async def list_pending(self, org_id: UUID, page: PageRequest) -> Page[Invitation]: ...
